apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "chart-nicolas.labels" . | nindent 4 }}
  {{- if .Values.secrets.name }}
  name: {{ .Values.secrets.name}}
  {{- else }}
  name: {{ include "chart-nicolas.fullname" . }}
  {{- end }}
type: Opaque
data:
{{- range $key, $val := .Values.secrets.data }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}