apiVersion: v1
kind: PersistentVolumClaim
metadata:
  name: {{ include "theia.fullname" . }}
  label: {{ include "theia.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resource:
    requests:
      storage: 2Gi
  storageClassName: longhorn
  volumeMode: FileSystem